#!/usr/bin/env bash

source $HOME/bin/m

# a is for audio
a(){
    # run through inputs, if we only have directories, shuffle + loop
    local only_dirs=1
    for thing in "$@" ; do
        if [ -f "$thing" ]; then
            only_dirs=0
        fi
    done

    local params="--no-video"
    if [ "$only_dirs" -eq 1 ]; then
        params="$params --shuffle --loop-playlist inf"
    fi
    m "$@" $params
}

if [ "${FUNCNAME[0]}" = "main" ]; then
	# this file wasn't sourced, execute.
	a "$@"
	exit $?
fi
