#!/usr/bin/env python3

import datetime as dt

import sys

DateTimeFormat="%Y-%m-%dT%H:%M"

def hours_to_seconds(hours):
    return hours*60*60

for line in sys.stdin:

    # line format is:
    #    date-awake
    #    , hour:min asleep (this might be the date before)
    #    , hour:min awake
    #    , time slept
    #    , notes

    if 'Date' in line:
        # first line has headers, skip
        continue;

    segments = line.split(',')

    date_awake = dt.datetime.strptime(segments[0] + " " + segments[2], '%y/%m/%d %H:%M')

    # just use the time delta to get the right date, parse the 3rd segment to get the real time.
    hours_sleep = float(segments[3])
    sleep_duration = dt.timedelta(0, hours_to_seconds(hours_sleep))
    date_asleep = date_awake - sleep_duration

    # time we fell asleep
    time_asleep = dt.datetime.strptime(segments[1], '%H:%M')

    date_asleep = dt.datetime(date_asleep.year, date_asleep.month, date_asleep.day, time_asleep.hour, time_asleep.minute)

    print("asleep", date_asleep.strftime(DateTimeFormat))
    print("awake", date_awake.strftime(DateTimeFormat))

