#!/bin/bash
#    init-dot-files - creates hard links to dot files, and generates others

if ! ls dot-init >/dev/null 2>/dev/null; then
	# sneaky way to check we're executing in the dot file repo
	echo "dot-init can only be used inside the dot file repo" 
	exit
fi

# Source the config stuff
source ".config/dot-config"

delete-generate(){
    mkdir -p "$GEN_DIR"
    
    for file in ` cd "$GEN_DIR" ; find . -type f ` ; do
        if [[ -f "$HOME/$file" ]]; then
		rm -v "$HOME/$file"
        fi
    done
}

delete-linking(){

    mkdir -p $SRC_DIR

    for file in ` cd $SRC_DIR ; find . -type f ` ; do
        if [[ -f "$HOME/$file" ]]; then
		rm -v "$HOME/$file"
        fi
    done
}

delete-linking
delete-generate

