#!/bin/bash
#    init-dot-files - creates hard links to dot files, and generates others

cd "`dirname "$(readlink -f "$0")"`"

do-submodules(){
    # submodules are symlinked using git
    cd "submodules/" ; make --no-builtin-rules --no-builtin-variables
}

do-linking(){
    config_dir="config"
    cat "${config_dir}/MAPPING" | dot-deploy --config "${config_dir}" --root "$HOME"
}

do-linking
do-submodules
