#!/usr/bin/env python3

import sys
import configparser

if __name__ == "__main__":

  if len(sys.argv) < 4:
    sys.stderr.write("wrong number of args for ini, requires 3 or more\n")
    sys.stderr.write(" usage: ini <file> <section> <key> [opt-value opt-value-list] \n")
    exit(1)

  _ignored, file_name, section, key, *opt_value = sys.argv
  cfg = configparser.ConfigParser()
  cfg.read([file_name])

  if len(opt_value) is 0:
    print(cfg[section][key])
  else: # len(opt_value) is 1
    if section not in cfg:
      cfg.add_section(section)
    cfg[section][key] = " ".join(opt_value)
    with open(file_name, "w") as f:
      cfg.write(f)


