#!/bin/bash
#    init-dot-files - creates hard links to all the dot files for us

SOURCE=".source"

linkFile(){
    out="$HOME/${1}{$2}"
    if [[ -f "$out" ]] ; then
        rm "$out"
    fi
    ln "$SOURCE/$1" "$out"
}

# first setup directories
for dir in ` cd $SOURCE ; find . -type d ` ; do
    if [[ ! -d "$HOME/$dir" ]]; then
        # directory doesn't exist
        mkdir -p "$HOME/$dir"
    fi
done # directories

for file in ` cd $SOURCE ; find . -type f ` ; do

    if [[ -f "$HOME/$file" ]]; then
        if ! diff "$HOME/$file" "$SOURCE/$file" > /dev/null ; then
            echo "$HOME/$file already exists and differs from $SOURCE/$file"
            echo "linked source to $file.1 instead"
            linkFile "$file" ".1"
        fi
    else
        # don't exist yet
        linkFile "$file"
    fi
done
