#!/usr/bin/env bash

usage(){
	echo "Usage: kiwi <storage-file> <command> <key>"
	echo " Kiwi is a simple command line key value store,"
	echo " that only supports simple text data."
	echo
	echo "Commands available:"
	echo " get - retrieve the value of the specified key, prints to stdout"
	echo " put - store the value to the specified key, reads from stdin"
	echo " match - retrieves all matching keys, prints keys to stdout"
	echo " remove - removes the specified key, prints the old value to stdout"
}

SQL="sqlite3"

STORE="$1" ; shift
COM=$1; shift
KEY="$1" ; shift

if [ $# -gt 0 ]; then
	echo "Error kiwi currently only supports a single key being specified" >> /dev/stderr
	exit 1
fi

if [ ! -f "$STORE" ]; then
	# create db if required
	echo "CREATE TABLE kiwi_store ( key text PRIMARY KEY ON CONFLICT REPLACE, value text );" | "$SQL" "$STORE"
fi

case $COM in
	get)
		echo -n "SELECT value FROM kiwi_store WHERE key = '$KEY';" | "$SQL" "$STORE"
	;;
	put)
		# 'sql' escaping
		# and subshell magic
		( echo -n "INSERT INTO kiwi_store(key,value) VALUES ( '"
		  echo $KEY | sed "s_'_''_g" ;
		  echo "', '" ;
		  # escapes standard input
		  sed "s_'_''_g" ;
		  echo "');" ) | "$SQL" "$STORE" 
	;;
	match)
		echo -n "SELECT key FROM kiwi_store WHERE key LIKE '$KEY';" | "$SQL" "$STORE"
	;;
	remove)
		echo -n "SELECT value FROM kiwi_store WHERE key = '$KEY';" | "$SQL" "$STORE"
		echo -n "DELETE FROM kiwi_store WHERE key = '$KEY';" | "$SQL" "$STORE"
	;;
	*)
		usage
		exit 2
	;;
esac
