#!/bin/sh

loaded=`pactl list modules short | grep 'module-bluetooth'`

load_module(){
	local module="$1" ; shift
	echo "$loaded" | grep "$module" > /dev/null

	if [ $? -ne 0 ]; then
		pactl load-module "$module" > /dev/null
		if [ $? -eq 0 ]; then
			echo "$module loaded..."
		fi
	else
		echo "$module already loaded."
	fi
}

load_module module-bluetooth-discover

