#!/bin/bash
#           lsbytesum - sum the number of bytes in a directory listing

read -d '' script <<- EOF

    BEGIN { size = 0.0 ; accuracy = 1 ;}
    /^-/  { size = size + \$5 }
    END   {
            mib = size/(1024*1024) ;
            print int(mib*accuracy)/accuracy ;
          }

EOF

#echo "$script"

echo `ls -al | awk -- "$script"`
