#!/bin/bash

shopt -s nullglob globstar

password_files=( $PASSWORD_STORE_DIR/**/*.gpg )
password_files=( "${password_files[@]##*${PASSWORD_STORE_DIR}/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu -p '>>>' "$@")

pass -c "$password"
