#!/bin/bash

path-prompt(){

	[ -n "$VIM" ] && echo -n "[vim] "

	radioactive="\u2622"
	[ "$PATH" != "$BASE_PATH" ] && echo -e "\e[0;31m${radioactive}\e[m" && exit

	echo ">"
}

# source trickery!
# the file wasn't sourced, but executed
if [ "$_" = "$0" ]; then
	path-prompt "$@"
fi
