#!/usr/bin/env bash

BROWSER=w3m
ARGS=""

if [[ $# -lt 1 ]]; then
	echo "usage: $0 search goes here"
	exit
else
	QUERY=` echo $@ | tr ' ' '+' `
	URL="http://google.ca/search?q=${QUERY}"
	"$BROWSER" $ARGS "$URL"
fi

