#!/bin/sh

# update table 'column = value' column value


if [ $# -lt 2 ]; then
	echo "Usage: $0 <table-name> <update-col> ... [-w where-clauses ...]" >> /dev/stderr
	echo "\tGiven a set of updates and a table name" >> /dev/stderr
	echo "\t generates a sqlite UPDATE command." >> /dev/stderr
	exit 1
fi

COUNT=1
TABLE="$1" ; shift

echo -n "UPDATE $TABLE SET "

while [ $# -gt 0 ]; do
	if [ "$1" = "-w" ]; then
		shift ; echo -n "WHERE $@ "
		break 
	else
		if [ $COUNT -eq 1 ]; then
			COUNT=$((COUNT+1))
		else
			echo -n ","
		fi
		echo -n " $1 "
	fi
	shift
done

echo ";"
