#!/bin/sh

if [ $# -lt 2 ]; then
	echo "Usage: $0 <table-name> <column value> ..." >> /dev/stderr
	echo "\tGiven a set of column values and a table name" >> /dev/stderr
	echo "\t generates a sqlite INSERT command." >> /dev/stderr
	exit 1
fi

echo -n "INSERT INTO $1 VALUES(" ; shift
while [ $# -gt 1 ]; do
	echo -n " '$1'," ; shift
done
echo " '$1' );"
