#!/usr/bin/env bash

# time capsule format:
# format    := headers questions
# headers   := '' | header '\n' headers
# header    := '#' key '=' value
# key       := 'memo' | 'expire'
# value     := ascii-newline+

# question format matters a little less.
# questions := '' | question '\n' questions
# question  := date ':' text
# date      := year '-' month '-' day
# text      := ascii*

HEADER="== TIME_CAPSULE =="
KEY_EXPIRE="expire"
KEY_MEMO="memo"

err(){
	echo -e "\e[31m" "$@" "\e[0m" >> /dev/stderr
}

_assert(){
	if [ $# -eq 0 ]; then
		err "Error empty assertion."
		exit 1
	fi
	"$@" > /dev/null 2> /dev/null
	if [ $? -ne 0 ]; then
		err "Error assertion failed: $@"
		exit 1
	fi
}

require-file(){
	_assert [ -n "$FILE" ]
	if [ ! -e "$FILE" ]; then
		err "Unable to find time capsule '$FILE'."
		err "Are you sure it exists?"
		exit 2
	fi
}

tc-create(){
	_assert [ -n "$FILE" ]
	if [ -e "$FILE" ]; then
		err "File '$FILE' already exists."
		err "Can not create time capsule."
		exit 2
	fi

	local input_date
	read -p "On what date can the capsule be opened? " input_date

	local open_date
	open_date="$(date -d "$input_date" "+%Y/%m/%d" 2> /dev/null )"
	if [ $? -ne 0 ]; then
		err "Unable to understand date '$input_date'."
		exit 2
	fi

	local input_memo
	echo "Enter a memo for the time capsule."
	read input_memo

	echo "# == TIME_CAPSULE ==" >> $FILE
	echo "# $KEY_EXPIRE = $open_date" >> $FILE
	echo "# $KEY_MEMO = $input_memo" >> $FILE

	echo Created.
}

tc-memo(){
	require-file
	echo "The capsule has the following memo:"
	echo -n "> "
	cat "$FILE" |
	  grep "# $KEY_MEMO =" |
	  sed "s/# $KEY_MEMO = //"
}

tc-add(){
	require-file
	echo "Press Ctrl-D when done."
	while read line ; do
		echo "$line" >> "$FILE"
	done
}

tc-view(){
	require-file

	local end_date="$(
	 cat "$FILE" |
	  grep "# $KEY_EXPIRE =" |
	  sed "s/# $KEY_EXPIRE = //")"

	# need to compare dates using seconds since epoch
	local end_date_s="$(date -d "$end_date" +%s )"
	local today_s=$(date -d 00:00 +%s)

	if [ $today_s -lt $end_date_s ]; then
		err "Time capsule hasn't expired yet."
		err "Please wait until $end_date."
		tc-memo
	else
		# strip out the headers before displaying the file
		cat "$FILE" |
		  grep -vE '^#' |
		  sensible-pager
	fi
}

COM="$1" ; shift
FILE="$1" ; shift

case $COM in
	create) tc-create "$@" ;;
	add) tc-add "$@" ;;
	view) tc-view "$@" ;;
	memo) tc-memo "$@" ;;
	*) err "command $COM not found" ;;
esac
