#!/bin/bash

# Creates a database of quotes that can be listed

DB="$PWD/quote.db"

# ensure the DB exists
if [ ! -f "$DB" ]; then
	echo "CREATE TABLE quotes ( quote TEXT );" | sqlite "$DB"
fi

ARGS="$@"

case $0 in
	*quotes)
		if [ $# -eq 0 ]; then
			exit
		fi
		sqlite-insert quotes "\"$ARGS\"" | sqlite "$DB"
		;;
	*quotes-list)
		if [ $# -gt 0 ]; then
			# SQL injection for flexibility. lol
			sqlite-select quotes \* quote LIKE "$ARGS" | sqlite "$DB"
		else
			sqlite-select quotes \* | sqlite "$DB"
		fi
		;;
esac
