#!/bin/bash

# the name of this source
SRC='commands'

# standard config reading stuff
config(){
	KEY="$1" ; shift
	if [ $# -gt 0 ]; then
		journal config "$SRC" "$KEY" "$@"
	else
		journal config "$SRC" "$KEY"
	fi
}

ensure-config(){
	KEY="$1" ; shift ; DEFAULT="$@"
	VALUE="$(config "$KEY" )"
	if [ -z "$VALUE" ];then
		config "$KEY" "$DEFAULT"
		VALUE="$DEFAULT"
	fi
	echo "$VALUE"
}

# stuff that should be in config
# this doesn't auto expand to $HOME, but embeds the string '$HOME' in the config
# it gets auto expanded when we read it.
PATH_AUGMENT="$(ensure-config augment-path '$HOME/bin/journal-bin/commands')"
ECHO_COMMANDS="$(ensure-config echo '')"
GEN_OUTPUT="$(journal config journal generated)"

CLEAN=0
FULL=0
INCR=0

if [ $# -eq 0 ]; then
	echo "$0: [--clean] [--full] [--incremental] file+"
	exit 1
fi

while [ $# -gt 0 ]; do
	case $1 in
		--full) FULL=1 ; CLEAN=1 ;;
		--clean) CLEAN=1 ;;
		--incremental) INCR=1 ;;
		*) # This is the start of the files/dirs for update/build
			break ;;
	esac
	shift
done

if [ $FULL -ne 0 -a $INCR -ne 0 ]; then
	# this should never happen
	echo "$0: --full and --incremental are exclusive, only one can be specified at a time" >> /dev/stderr
	exit 1
fi
if [ $CLEAN -ne 0 -a -d "$GEN_OUTPUT" ]; then
	# since we toss all of out output into `journal config journal generated` we don't have to do anythng
	echo -n
fi

if [ $INCR -ne 0 -o $FULL -ne 0 ]; then

	ARGS="$@"
	if [ $FULL -ne 0 ]; then
		ARGS="$( echo ${ARGS}/* )"
	fi

	# as far as journal-parse is concerned, there's no difference
	# between full and incremental, except for the files that get
	# passed to it

	cat $ARGS |
	"$HOME/bin/journal-bin/journal-parse"	\
		--path "$PATH_AUGMENT:$PATH"	\
		--output "$GEN_OUTPUT"		\
		$ECHO_COMMANDS			\
		--stdin

fi

