#!/usr/bin/env bash

# this should probably configurable.
ENTRY_SEPERATOR="---------------"

# accepts archivist replay on stdin,
# optionally takes a command name.
get-bang-command(){
	_assert [ $# -gt 0 ]
	COMMANDS="$( echo "$@" | sed 's_ \+_|!_g' )"

	grep -E "^(${ENTRY_SEPERATOR}|!${COMMANDS})" | remove-start
}

remove-start(){
	sed 's/^!//'
}

run-build(){
	# these are the same.
	run-incremental "$@"
}

run-incremental(){
	_assert_variable COMMAND_NAMES
	_assert_function HANDLER
	cat "$1" |
	 get-bang-command $COMMAND_NAMES |
	 HANDLER
}

run-query(){
	_assert_variable FILE
	cat "$FILE"
}


