#!/bin/bash

# this file gets sourced by other journal sources,
#  so they don't have to write these functions again.

# this file assumes the following:
# * SRC is set

if [ -z "$SRC" ]; then
	echo "error: \$SRC not defined when sourceing $0"
	exit 2
fi

# were to put all the files we generate
GENERATED="$(journal config journal generated)"

# standard config reading stuff
config(){
	KEY="$1" ; shift
	if [ $# -gt 0 ]; then
		journal config "$SRC" "$KEY" "$*"
	else
		journal config "$SRC" "$KEY"
	fi
}

ensure-config(){
	KEY="$1" ; shift ;
	VALUE="$( config "$KEY" )"
	if [ -z "$VALUE" ];then
		config "$KEY" "$@"
		VALUE="$@"
	fi
	echo "$VALUE"
}

