#!/usr/bin/env bash

ENTRY_SEPERATOR="$(journal config journal entry-seperator)"

read -d '' SCRIPT <<- EOF
	BEGIN { file = "" }
        /^$ENTRY_SEPERATOR/ {
		if( file != "" ){
			print file
		}
                # strip out any extra date information that
                # might have been put in the entry date line
                line = \$1 ;
                gsub( "$ENTRY_SEPERATOR", "", line );
                len = split( line, A, "/" );
                name=A[1];
                for(i=2; i <= len; i++){
                        name = A[i] "-" name;
                }
                file = name
                gsub( "-", "/", name )
                \$0 = "$ENTRY_SEPERATOR" name ;
        }
        { print \$0 >> file }
	END { print file }
EOF

awk "$SCRIPT" < /dev/stdin > /dev/stdout
