#!/bin/bash

# were to put all the files we generate
GENERATED="$(journal config journal generated)"

cd "$GENERATED"

if [ $? -ne 0 ]; then
	echo "Unable to find index file run 'journal build index'" >> /dev/stderr
	exit 1
fi

# temporary storage file for index thing to show the user,
tmp=`mktemp`

# all of our arguments get passed to search++
search++ $@ > "$tmp"

dates=$(cat "$tmp" | awk '{ print $4 }' | tr '\n' ' ' )

# display the results before the actual entries
sensible-pager "$tmp"

# delete the temporary file, asap
rm "$tmp"

# display the entries
journal view $dates

