#!/usr/bin/env bash

source "$(journal config journal library)"

FILE="$GENERATED/swish++.index"

# override this function because it's not needed
run-init(){
	echo -n
}

run-build(){
	BIN="$(journal config journal bin)"
	# the argument passed is a file, unfortunately index++
	# doesn't like to index this, and just returns the one
	# file for any query. So first we have to break up the
	# one file, and then index a bunch of files seperately.

	tmp="$(mktemp --directory)" ; cd "$tmp"
	cat "$1" | "$BIN/journal-split"

	# after splitting the file we can index it properly
	cd "$GENERATED" ; index++ -e text:* "$tmp"

	# cleanup after ourselves.
	rm -r "$tmp"
}

run-incremental(){
	cd "$GENERATED"

	# the argument passed is a file
	index++ --incremental -e text:* "$1"

	# swish++ creates a new index that is the old one with
	# the incremental changes, so we have to replace the
	# old index with the new one
	mv swish++.index.new swish++.index
}

run-query(){
	if [ $# -eq 0 ]; then
		man search++
		exit
	fi

	cd "$GENERATED"
	# temporary storage file for index thing to show the user,
	tmp=`mktemp`

	# all of our arguments get passed to search++, since
	# the user should know how to query us.
	search++ "$@" > "$tmp"

	dates=$(cat "$tmp" | awk '{ print $4 }' | tr '\n' ' ' )

	# display the results before the actual entries
	sensible-pager "$tmp"

	# delete the temporary file, asap
	rm "$tmp"

	# display the entries
	journal view $dates
}

run "$@"
