#!/usr/bin/env bash

SRC=commands

source "$(journal config journal library)"
source "$(config library)"

FILE="$GENERATED/quotes.txt"

# replace a bunch of things that we need because this isn't a .txt file we're creating

run-init(){
	_assert_variable FILE
	touch "$FILE"
}

run-clean(){
	_assert_variable FILE
	rm "$FILE"
}

run-query(){
	if [ $# -gt 0 ]; then
		cat "$FILE" | grep -iE "$*"
	else
		cat "$FILE"
	fi | sed 's_\\n_\n_g'
}

get-bang-command(){
	grep -E "^!quotes +" |
	# remove the start of lines
	sed 's_^!quotes \+__'
}

COMMAND_NAMES="quotes"
HANDLER(){
	cat >> "$FILE"
}

run "$@"
