#!/usr/bin/env bash

# this is part of a library of functions, so we set SRC funny
SRC=commands

# For nice things to interact with the journal
source "$(journal config journal library)"

# Required for use of the standard journal-library functions
FILE="$GENERATED/life.md"
INITIAL_HEADER="My Life\n===============\n"

# For all the functiosn that we use for command stuff
source "$(config library)"

# required for use of the standard commands-library functions
COMMAND_NAMES="event event-start event-end"
HANDLER(){
	local DATE=""
	while read line ; do
		case "$line" in
			${ENTRY_SEPERATOR}*)
				VAR="$( echo $line | sed 's_[^ ]* \([^ ]*\) .*$_\1_' )"
				month="${VAR#*-}" ; month="${month%-*}"
				DATE="${VAR##*-}/$month/${VAR%%-*}"
			;;
			*)
				_assert [ ! -z "$DATE" ]
				run-line "$DATE" $line
			;;
		esac
	done
}

run-line(){
	local DATE="$1" ; shift
	local COM="$1" ; shift

	case $COM in
		event)
			echo "- ${DATE} $@" >> "$FILE"
		;;
		event-start)
			echo "- ${DATE}-~ $@" >> "$FILE"
		;;
		event-end)
			tmp=`mktemp`
			sed "s_^- \(../../....\)-~ $*_- \1-${DATE} $*_" "$FILE" > "$tmp"
			mv "$tmp" "$FILE"
		;;
		*)
			echo "Error with line: $@" > /dev/stderr
		;;
	esac
}

run "$@"
