#!/usr/bin/env bash

date-portions(){
	echo "$@" | grep -o '-' | wc -l
}

update-date(){
	local DATE="$1" ; shift

	while [ `date-portions $DATE` -lt 2 ]; do
		DATE="${DATE}-01"
	done

	echo $DATE
}

update-file(){
	local file="$1" ; shift
	local date="$(update-date "$file")"

	echo $file

	# output the file
	cat "$file" |
	# all lines past the first
	 tail -n +2 |
	# send it to the archive
	 archivist -a $ARCHIVE submit "$date"
}

ARCHIVE="/media/jex/simulacrum/Journal/journal-archive"

for file in * ; do
	update-file "$file"
done
