#!/bin/bash

# This script is meant to be copied into ~/.steam/bin*/ (or hard linked) and
# intercept calls to fossilize_replay, which needs to get moved to
# fossilize_replay.real
#
# See ~/bin/steam for the script that handles the setup for this.

# Because of this, this script can't be symlinked.
dir="$(dirname "$(readlink -f "$0")")"

# Write some debugging info out to our fifo pubsub stuff.
(date --iso-8601=seconds | tr '\n' ' ' ; echo "=> fossilize_replay $@") |
  pubsub-fifo publish fossilize_replay 2>&1 > /dev/null

exec nice --adjust 10 ionice -c 3 prlimit -rss 6442450944 "${dir}/fossilize_replay.real" "$@"
